manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: f27993070f3f20220268a044673677351656811a
      import: app/west.yml
  self:
    path: config